import './style.css';
import {openEditor} from './editor/editor';
import {generate} from './levels/generator';
import {analyze} from './core/solver';
import {SceneManager} from './game/scene';
import {AudioEngine} from './game/audio';
import {LevelManager} from './levels/manager';
import {SaveManager} from './storage/save';
import {applyMove,canArrowEscape,getAvailableMoves,type Arrow,type Level} from './core/puzzle';
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<header><a class="brand" href="./" aria-label="VECTOR Start"><span class="brandmark">↗</span> VECTOR<span class="brand-dot">®</span></a><span class="tagline">FREIER RAUM. KLARER KOPF.</span><div class="top-actions"><button id="levels-button" class="text-button">▦ <span>Levelauswahl</span></button><button id="settings-button" class="icon-button" aria-label="Einstellungen">⚙</button></div></header>
<main><aside class="intro"><div class="eyebrow"><span class="tiny-line"></span> EIN KLEINER MOMENT FÜR DICH</div><h1>Alles hat<br>seine <em>Richtung.</em></h1><p class="intro-copy">Dreh die Perspektive. Finde freie Wege.<br>Und schaffe Raum, Pfeil für Pfeil.</p><div class="chapter-card"><span id="chapter" class="eyebrow">01 / ANKOMMEN</span><h2 id="level-name"></h2><p id="lesson"></p><div class="progress-track"><span id="progress-fill"></span></div><div class="progress-caption"><span id="progress-text"></span><span id="level-fraction"></span></div></div><div class="quiet-note"><span>◎</span> Kein Timer. Kein Druck.<br><span></span> Nur du und der nächste freie Weg.</div></aside>
<section class="play-space" aria-label="Spielfeld"><div class="stage-top"><span class="pill" id="mode-pill">● ZEN-MODUS</span><span class="stage-level" id="stage-level"></span></div><div id="scene"></div><div class="axis-legend" aria-hidden="true"><span class="x-dot"></span> X <span class="y-dot"></span> Y <span class="z-dot"></span> Z</div><div id="status" role="status" aria-live="polite"></div><div class="stage-bottom"><span class="gesture">↔ Ziehen zum Drehen <span>·</span> Scrollen zum Zoomen</span><button id="camera-button" class="icon-button" aria-label="Kamera zentrieren" title="Kamera zentrieren"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="12" cy="12" r="6"/><path d="M12 2v5m0 10v5M2 12h5m10 0h5"/></svg></button></div></section>
<div class="game-toolbar"><span id="remaining-label"></span><div><button id="restart-button" class="text-button">↻ <span>Neustart</span></button><button id="access-button" class="text-button">⌨ <span>Pfeilliste</span></button><button id="hint-button" class="hint-button">✧ <span>Ein kleiner Hinweis</span></button></div></div></main>
<footer><span>WENIGER ABLENKUNG. MEHR PERSPEKTIVE.</span><button id="editor-button" class="text-button">Werkstatt ↗</button><span>OHNE WERBUNG · OHNE TRACKING</span></footer>
<dialog id="modal"><button class="modal-close icon-button" aria-label="Schließen">×</button><div id="modal-content"></div></dialog><div id="dev-panel" hidden></div>`;
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const modal=$<HTMLDialogElement>('#modal'),content=$('#modal-content');
export function openModal(html:string){content.innerHTML=html;if(!modal.open)modal.showModal();}
$('.modal-close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
const manager=new LevelManager(),save=new SaveManager(),audio=new AudioEngine();audio.enabled=save.data.sound;
let scene:SceneManager,state:Arrow[]=[],level:Level,mistakes=0,hints=0,hintStage=0,busy=false,custom=false;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function status(text:string){$('#status').textContent=text;}
function refresh(){const removed=level.arrows.length-state.length;$('#chapter').textContent=level.chapter;$('#level-name').textContent=level.name;$('#lesson').textContent=level.hint;$('#level-fraction').textContent=custom?'WERKSTATT':`${String(level.id).padStart(2,'0')} / ${manager.levels.length}`;$('#stage-level').textContent=`LEVEL ${String(level.id).padStart(2,'0')}`;$('#progress-text').textContent=`${removed} von ${level.arrows.length} gelöst`;$('#progress-fill').style.width=`${removed/level.arrows.length*100}%`;$('#remaining-label').textContent=`${state.length} ${state.length===1?'Pfeil':'Pfeile'} verbleibend`;$('#mode-pill').textContent=save.data.mode==='zen'?'● ZEN-MODUS':`◇ CHALLENGE · ${mistakes} FEHLVERSUCHE`;}
function start(l:Level,isCustom=false){level=l;custom=isCustom;state=l.arrows.map(a=>({...a}));mistakes=0;hints=0;hintStage=0;busy=false;scene.setArrows(state);refresh();status('Welcher Pfeil hat freie Bahn?');if(!custom){save.data.current=l.id;save.persist();}if(!save.available)status('Speichern ist im Browser nicht verfügbar. Diese Sitzung funktioniert trotzdem.');}
function complete(){audio.play('win');const stars=custom?0:save.complete(level.id,mistakes,hints,manager.levels.length);openModal(`<div class="eyebrow">${custom?'WERKSTATT':'GUT GEMACHT'}</div><div class="win-symbol">✧</div><h2>Raum geschaffen.</h2><p>Ein neuer Blick. Ein freier Kopf.</p>${save.data.mode==='challenge'&&!custom?`<div class="stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div>`:''}<div class="win-stats"><span><strong>${level.arrows.length}</strong>Pfeile gelöst</span><span><strong>${mistakes}</strong>Fehlversuche</span><span><strong>${hints}</strong>Hinweise</span></div><button id="next-button" class="primary">${custom?'Zurück zur Kampagne':level.id<manager.levels.length?'Weiter zum nächsten Level ↗':'Alle Levels geschafft ✓'}</button><button id="win-levels" class="text-button">Zur Levelauswahl</button>`);$('#next-button').onclick=()=>{modal.close();start(manager.get(custom?save.data.current:Math.min(manager.levels.length,level.id+1)));};$('#win-levels').onclick=showLevels;}
function pick(id:string){if(busy||!state.some(a=>a.id===id))return;scene.highlight([]);if(!canArrowEscape(state,id)){mistakes++;scene.shake(id);audio.play('blocked');status('Noch nicht frei. Ein anderer Pfeil steht im Weg.');refresh();return;}busy=true;audio.play('move');state=applyMove(state,id);hintStage=0;refresh();status('Freie Bahn.');scene.fly(id,()=>{busy=false;if(!state.length)complete();});}
function showLevels(){audio.play('ui');openModal(`<div class="eyebrow">DEIN WEG DURCH VECTOR</div><h2>Eine neue Perspektive.</h2><p>${Object.keys(save.data.results).length} von ${manager.levels.length} Levels abgeschlossen</p><div class="level-grid">${manager.levels.map(l=>`<button data-level="${l.id}" ${l.id>save.data.unlocked?'disabled':''} class="level-tile ${save.data.results[l.id]?'done':''} ${l.id===level.id?'current':''}" aria-label="Level ${l.id}: ${esc(l.name)}${l.id>save.data.unlocked?', gesperrt':''}"><span>${String(l.id).padStart(2,'0')}</span><small>${l.id>save.data.unlocked?'GESPERRT':save.data.results[l.id]?'★'.repeat(save.data.results[l.id].stars):'OFFEN'}</small></button>`).join('')}</div>`);content.querySelectorAll<HTMLButtonElement>('[data-level]').forEach(b=>b.onclick=()=>{start(manager.get(Number(b.dataset.level)));modal.close();});}
function showSettings(){openModal(`<div class="eyebrow">SO, WIE DU MAGST</div><h2>Dein kleiner Freiraum.</h2><label class="setting">Sanfte Klänge <input id="sound" type="checkbox" ${save.data.sound?'checked':''}></label><label class="setting">Spielmodus <select id="mode"><option value="zen" ${save.data.mode==='zen'?'selected':''}>Zen · ohne Bewertung im Spiel</option><option value="challenge" ${save.data.mode==='challenge'?'selected':''}>Challenge · Sterne & Fehlversuche</option></select></label><p class="small">3 Sterne ohne Fehler und Hinweise, 2 Sterne bei höchstens 3 Fehlversuchen, sonst 1 Stern. Jeder gelöste Level zählt.</p><p class="small">Der Fortschritt bleibt auf diesem Gerät. Keine Konten, keine Werbung, keine Übertragung deiner Spieldaten.</p><button id="reset-save" class="danger-button">Gesamten Spielstand zurücksetzen</button>`);$<HTMLInputElement>('#sound').onchange=e=>{save.data.sound=(e.target as HTMLInputElement).checked;audio.enabled=save.data.sound;save.persist();audio.play('ui');};$<HTMLSelectElement>('#mode').onchange=e=>{save.data.mode=(e.target as HTMLSelectElement).value as 'zen'|'challenge';save.persist();refresh();};$('#reset-save').onclick=()=>{openModal('<h2>Wirklich neu beginnen?</h2><p>Alle freigeschalteten Levels und Bestleistungen werden auf diesem Gerät gelöscht.</p><button id="confirm-reset" class="primary">Ja, Spielstand löschen</button><button id="cancel-reset" class="text-button">Abbrechen</button>');$('#cancel-reset').onclick=showSettings;$('#confirm-reset').onclick=()=>{save.reset();audio.enabled=false;modal.close();start(manager.get(1));};};}
function showArrows(){openModal(`<div class="eyebrow">ALTERNATIVE BEDIENUNG</div><h2>Alle Pfeile im Blick.</h2><p>Wähle einen Pfeil. Die Prüfung entspricht exakt dem 3D-Spiel.</p><div class="arrow-list">${state.map(a=>`<button class="list-arrow" data-arrow="${esc(a.id)}"><strong>${esc(a.id)}</strong><span>(${a.x}, ${a.y}, ${a.z})</span><b>${a.direction.replace('POS_','+').replace('NEG_','−')}</b></button>`).join('')}</div><p class="small">Im Spielfeld: Pfeiltasten drehen, + / − zoomen und 0 zentriert die Kamera.</p>`);content.querySelectorAll<HTMLButtonElement>('[data-arrow]').forEach(b=>b.onclick=()=>{modal.close();pick(b.dataset.arrow!);});}
$('#levels-button').onclick=showLevels;$('#settings-button').onclick=showSettings;$('#access-button').onclick=showArrows;
$('#restart-button').onclick=()=>{if(!busy)start(level,custom);};$('#camera-button').onclick=()=>scene.resetCamera();
$('#hint-button').onclick=()=>{if(busy||!state.length)return;hints++;hintStage=Math.min(3,hintStage+1);const id=getAvailableMoves(state)[0];if(!id){status('Hier ist kein freier Zug möglich. Prüfe das Level in der Werkstatt.');return;}const a=state.find(a=>a.id===id)!;if(hintStage===1)status('Suche außen. Folge der Pfeilspitze: Ist die ganze Linie frei?');if(hintStage===2){scene.highlight(state.filter(b=>b.y===a.y).map(b=>b.id));status(`Schau auf die markierte Ebene bei Y = ${a.y}.`);}if(hintStage===3){scene.highlight([id]);status(`Pfeil ${id} hat freie Bahn. Du findest ihn auch in der Pfeilliste.`);}};
window.addEventListener('keydown',e=>{if(modal.open||!scene)return;const k=e.key;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','0'].includes(k)){e.preventDefault();if(k.startsWith('Arrow'))scene.turn(k==='ArrowLeft'?-.15:k==='ArrowRight'?.15:0,k==='ArrowUp'?-.15:k==='ArrowDown'?.15:0);else if(k==='0')scene.resetCamera();else scene.zoom(k==='+'?.85:1.15);}});
$('#editor-button').onclick=()=>{if(!busy)openEditor(modal,content,level,l=>start(l,true));};
async function boot(){try{await manager.load();scene=new SceneManager($('#scene'));scene.onPick=pick;scene.onError=()=>status('Die 3D-Verbindung wurde unterbrochen. Bitte lade die Seite neu.');start(manager.get(Math.min(save.data.current,manager.levels.length)));if(new URLSearchParams(location.search).has('dev')){const panel=$('#dev-panel');panel.hidden=false;scene.setGrid(true);scene.onFrame=(fps,calls)=>{const a=analyze(state);panel.textContent=`FPS ${fps.toFixed(0)} · Draw calls ${calls} · Level ${level.id} · Pfeile ${state.length} · freie Züge ${a.startMoves.length} · lösbar ${a.solvable} · Tiefe ${a.dependencyDepth}`;};}if(import.meta.env.DEV){Object.assign(window,{__vector:{get state(){return state;},get level(){return level;},get busy(){return busy;},start:(id:number)=>start(manager.get(id)),startGenerated:(count:number)=>start(generate({seed:42,count,dimensions:[9,9,9],shape:'block'}),true),moves:()=>getAvailableMoves(state),project:(id:string)=>scene.project(id),pick,scene}});}}catch(e){openModal(`<h2>VECTOR konnte nicht starten.</h2><p>${esc(e instanceof Error?e.message:'Unbekannter Fehler')}</p><p>Bitte verwende einen aktuellen Browser mit WebGL und lade die Seite erneut.</p>`);}}
void boot();

if(import.meta.env.PROD&&'serviceWorker' in navigator){window.addEventListener('load',()=>{void navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`).catch(()=>{console.info('Offline-Modus ist in diesem Browser nicht verfügbar.');});});}
